version: '3'
services:
  hypothesis-h:
    image: science_history_institute/hypothesis_service
    depends_on:
      - postgres
      - elasticsearch
      - elasticsearchold
      - rabbit
    ports:
      - '127.0.0.1:5000:5000'
    # volumes:
    #   - ./hypothesis-service:/var/lib/hypothesis
    environment:
      # - APP_URL=http://localhost:5000
      # - AUTHORITY=localhost
      # - BROKER_URL=amqp://guest:guest@rabbit:5672//
      # - DATABASE_URL=postgresql://postgres@postgres/postgres
      # - ELASTICSEARCH_HOST=http://elasticsearchold:9200
      # - ELASTICSEARCH_URL=http://elasticsearch:9201
      # - SECRET_KEY=notasecret
      - PIP_REQUIRE_VIRTUALENV = 0
    env_file:
      - .env
    network_mode: "host"
  hypothesis-client:
    image: science_history_institute/hypothesis_client
    ports:
      - '127.0.0.1:3001:3001'
    # volumes:
    #   - ./hypothesis-client:/var/lib/hypothesis-client
    # depends_on:
    #   - hypothesis-h
    network_mode: "host"
    env_file:
      - .env
  postgres:
    image: postgres:9.4-alpine
    ports:
      - '127.0.0.1:5432:5432'
  elasticsearch:
    image: hypothesis/elasticsearch:latest
    ports:
      - '127.0.0.1:9201:9200'
    environment:
      - discovery.type=single-node
  elasticsearchold:
    image: nickstenning/elasticsearch-icu
    ports:
      - '127.0.0.1:9200:9200'
  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
  community_history_platform:
    image: science_history_institute/community_history_platform
    ports:
      - '127.0.0.1:5050:5050'
    network_mode: "host"
    env_file:
      - .env
