version: '3'
services:
  hypothesis-h:
    build:
      context: .
      dockerfile: ./Dockerfile_service
      args:
        DEVELOPMENT: "true" 
    depends_on:
      - postgres
      - elasticsearch
      - elasticsearchold
      - rabbit
    ports:
      - '127.0.0.1:5000:5000'
    volumes:
      - hypothesis-service:/var/lib/hypothesis
    environment:
      # - APP_URL=http://localhost:5000
      # - AUTHORITY=localhost
      # - BROKER_URL=amqp://guest:guest@rabbit:5672//
      # - DATABASE_URL=postgresql://postgres@postgres/postgres
      # - ELASTICSEARCH_HOST=http://elasticsearchold:9200
      # - ELASTICSEARCH_URL=http://elasticsearch:9201
      # - SECRET_KEY=notasecret
      - PIP_REQUIRE_VIRTUALENV=0
      - CLIENT_URL=$HYPOTHESIS_CLIENT_URL
      - CLIENT_OAUTH_ID=$HYPOTHESIS_CLIENT_ID
    env_file:
      - .env
    network_mode: "host"
  hypothesis-client:
    build:
      context: .
      dockerfile: ./Dockerfile_client
    ports:
      - '127.0.0.1:3001:3001'
    # volumes:
    #   - ./hypothesis-client:/var/lib/hypothesis-client
    # depends_on:
    #   - hypothesis-h
    network_mode: "host"
    env_file:
      - .env
  postgres:
    image: postgres:9.4-alpine
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data
  elasticsearch:
    image: hypothesis/elasticsearch:latest
    ports:
      - '127.0.0.1:9201:9200'
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
  elasticsearchold:
    image: nickstenning/elasticsearch-icu
    ports:
      - '127.0.0.1:9200:9200'
    volumes:
      - elasticsearcholddata:/usr/share/elasticsearch/data
  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
  community_history_platform:
    build:
      context: .
      dockerfile: ./Dockerfile_app
    ports:
      - '127.0.0.1:5050:5050'
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./community_history_platform/flask/app:/var/lib/community_history_platform/app
  nginx:
    image: nginx:alpine
    ports:
      - "81:81"
    volumes:
      - ./nginx_server.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
volumes:
    hypothesis-service:
    elasticsearchdata:
    elasticsearcholddata:
    postgresdata:
